# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import empy
from empy.models.organization_list import OrganizationList  # noqa: E501
from empy.rest import ApiException

class TestOrganizationList(unittest.TestCase):
    """OrganizationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OrganizationList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationList`
        """
        model = empy.models.organization_list.OrganizationList()  # noqa: E501
        if include_optional :
            return OrganizationList(
                meta = {"next":{"href":"href"},"total":0,"last":{"href":"href"},"self":{"href":"href"},"first":{"href":"href"}}, 
                organizations = [
                    {"website":"website","address":{"country":"country","address":"address","address2":"address2","city":"city","coordinates":{"latitude":"latitude","longitude":"longitude"},"state":"state","zip_code":"zip_code"},"projects":[{"href":"href"},{"href":"href"}],"credit_amount":0.8008282,"created_at":"2000-01-23 04:56:07+00:00","description":"description","billing_address":{"country":"country","address":"address","address2":"address2","city":"city","coordinates":{"latitude":"latitude","longitude":"longitude"},"state":"state","zip_code":"zip_code"},"memberships":[{"href":"href"},{"href":"href"}],"enforce_2fa_at":"2000-01-23 04:56:07+00:00","twitter":"twitter","updated_at":"2000-01-23 04:56:07+00:00","terms":6,"members":[{"href":"href"},{"href":"href"}],"name":"name","logo":"","customdata":"{}","id":"046b6c7f-0b8a-43b9-b35d-6489e6daee91"}
                    ], 
                href = ''
            )
        else :
            return OrganizationList(
        )
        """

    def testOrganizationList(self):
        """Test OrganizationList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
