# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import empy
from empy.models.plan_specs import PlanSpecs  # noqa: E501
from empy.rest import ApiException

class TestPlanSpecs(unittest.TestCase):
    """PlanSpecs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PlanSpecs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanSpecs`
        """
        model = empy.models.plan_specs.PlanSpecs()  # noqa: E501
        if include_optional :
            return PlanSpecs(
                cpus = [
                    {"count":2,"type":"type"}
                    ], 
                drives = [
                    {"size":"3.84TB","count":7,"type":"HDD","category":"boot"}
                    ], 
                nics = [
                    {"count":2,"type":"1Gbps"}
                    ], 
                features = {"txt":True,"uefi":True,"raid":True}, 
                href = ''
            )
        else :
            return PlanSpecs(
        )
        """

    def testPlanSpecs(self):
        """Test PlanSpecs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
