# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import empy
from empy.api.organizations_api import OrganizationsApi  # noqa: E501
from empy.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = empy.api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_organization(self):
        """Test case for create_organization

        Create an organization  # noqa: E501
        """
        pass

    def test_create_organization_project(self):
        """Test case for create_organization_project

        Create a project for the organization  # noqa: E501
        """
        pass

    def test_find_organization_projects(self):
        """Test case for find_organization_projects

        Retrieve all projects of an organization  # noqa: E501
        """
        pass

    def test_find_organizations(self):
        """Test case for find_organizations

        Retrieve all organizations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
