# coding: utf-8

"""
    Metal API

    desc  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import empy
from empy.models.project_list import ProjectList  # noqa: E501
from empy.rest import ApiException

class TestProjectList(unittest.TestCase):
    """ProjectList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ProjectList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectList`
        """
        model = empy.models.project_list.ProjectList()  # noqa: E501
        if include_optional :
            return ProjectList(
                meta = {"next":{"href":"href"},"total":0,"last":{"href":"href"},"self":{"href":"href"},"first":{"href":"href"}}, 
                projects = [
                    {"devices":[{"href":"href"},{"href":"href"}],"volumes":[{"href":"href"},{"href":"href"}],"created_at":"2000-01-23 04:56:07+00:00","memberships":[{"href":"href"},{"href":"href"}],"bgp_config":{"href":"href"},"max_devices":"{}","ssh_keys":[{"href":"href"},{"href":"href"}],"updated_at":"2000-01-23 04:56:07+00:00","invitations":[{"href":"href"},{"href":"href"}],"members":[{"href":"href"},{"href":"href"}],"name":"name","network_status":"{}","customdata":"{}","id":"046b6c7f-0b8a-43b9-b35d-6489e6daee91","payment_method":{"href":"href"}}
                    ], 
                href = ''
            )
        else :
            return ProjectList(
        )
        """

    def testProjectList(self):
        """Test ProjectList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
